from rest_framework_extensions.key_constructor import bits
from rest_framework_extensions.key_constructor.constructors import DefaultKeyConstructor

from outpost.base.key_constructors import UpdatedAtKeyBit
