# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 09:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0011_auto_20170619_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('mac', netfields.fields.MACAddressField(db_index=True, primary_key=True, serialize=False)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('seen', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('mac', netfields.fields.MACAddressField(db_index=True, primary_key=True, serialize=False)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('deployed', models.DateTimeField(auto_now_add=True)),
                ('seen', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Level')),
            ],
        ),
    ]
