# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positioning', '0003_auto_20170627_1047'),
    ]

    operations = [
            migrations.DeleteModel('Beacon'),
            migrations.DeleteModel('AccessPoint'),
    ]
