# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170928_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campusonline.Room'),
        ),
    ]
