# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170928_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('registered',)},
        ),
        migrations.AddField(
            model_name='entry',
            name='autoend',
            field=models.BooleanField(default=False),
        ),
    ]
