# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:12
from __future__ import unicode_literals

from django.db import migrations


def convert_entries(apps, schema_editor):
    Entry = apps.get_model('attendance', 'Entry')
    CampusOnlineEntry = apps.get_model('attendance', 'CampusOnlineEntry')
    for e in Entry.objects.all():
        coe = CampusOnlineEntry(
            incoming=e
        )
        coe.state = e.state
        coe.ended = e.quit
        coe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20180725_1517'),
    ]

    operations = [
        migrations.RunPython(
            convert_entries,
            reverse_code=migrations.RunPython.noop
        ),
    ]
