# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models
from ...base.fields import ChoiceArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20180725_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='behaviour',
            field=ChoiceArrayField(base_field=models.CharField(choices=[('outpost.attendance.plugins.DebugTerminalBehaviour', 'Debugger'), ('outpost.attendance.plugins.StatisticsTerminalBehaviour', 'Statistics'), ('outpost.attendance.plugins.CampusOnlineTerminalBehaviour', 'CAMPUSonline')], max_length=256), default=list, size=None),
        ),
    ]
