# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0044_auto_20190225_1708'),
        ('attendance', '0012_auto_20190226_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='room',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campusonline.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='student',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campusonline.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terminal',
            name='behaviour',
            field=outpost.django.base.fields.ChoiceArrayField(base_field=models.CharField(choices=[('outpost.django.attendance.plugins.CampusOnlineTerminalBehaviour', 'CAMPUSonline'), ('outpost.django.attendance.plugins.StatisticsTerminalBehaviour', 'Statistiken'), ('outpost.django.attendance.plugins.DebugTerminalBehaviour', 'Debugger')], max_length=256), default=list, size=None),
        ),
    ]
