DDL

  CREATE OR REPLACE FORCE VIEW "API"."FORSCHUNG_ART_L" ("FORSCHUNG_ART_ID", "FORSCHUNG_ART_DE", "FORSCHUNG_ART_EN") AS 
  SELECT
FORSCHUNG_ART_ID,
	FORSCHUNG_ART_DE,
	FORSCHUNG_ART_EN
FROM rio.FORSCHUNG_ART_L;

  CREATE OR REPLACE FORCE VIEW "API"."GELDGEBER" ("GELDGEBER_ID", "GELDGEBER_DE", "GELDGEBER_EN", "STRASSE", "ORT", "POSTLEITZAHL", "LAND_ID", "URL", "GELDGEBER_TYP_ID") AS 
  SELECT
geldgeber_id,
GELDGEBER_DE,
GELDGEBER_EN,
STRASSE,
ORT,
POSTLEITZAHL,
LAND_ID,
URL,
GELDGEBER_TYP_ID --GELDGEBER_TYP_L
FROM rio.geldgeber;

  CREATE OR REPLACE FORCE VIEW "API"."GELDGEBER_TYP_L" ("GELDGEBER_TYP_ID", "GELDGEBER_TYP_DE", "GELDGEBER_TYP_EN", "GELDGEBER_TYP_KURZ") AS 
  SELECT
GELDGEBER_TYP_ID,
	GELDGEBER_TYP_DE,
	GELDGEBER_TYP_EN,
	GELDGEBER_TYP_KURZ
FROM rio.GELDGEBER_TYP_L;

  CREATE OR REPLACE FORCE VIEW "API"."LAND_L" ("LAND_ID", "LAND_DE", "LAND_EN") AS 
  SELECT
LAND_ID,
	LAND_DE,
	LAND_EN
FROM rio.LAND_L;

  CREATE OR REPLACE FORCE VIEW "API"."ORGEINHEIT_PUBLIKATION" ("PUBLIKATION_ID", "MEDONLINE_ID") AS 
  SELECT
op.PUBLIKATION_ID,
o.MEDONLINE_ID
FROM 
RIO.ORGEINHEIT_PUBLIKATION op
JOIN
RIO.ORGEINHEIT o
ON op.ORGEINHEIT_ID = o.ORGEINHEIT_ID;

  CREATE OR REPLACE FORCE VIEW "API"."ORG_PARTNER_PROJEKTFUNKTION_L" ("ORG_PARTNER_PROJEKTFUNKTION_ID", "ORG_PARTNER_PROJEKTFUNKTION_DE", "ORG_PARTNER_PROJEKTFUNKTION_EN") AS 
  SELECT
ORG_PARTNER_PROJEKTFUNKTION_ID,
	ORG_PARTNER_PROJEKTFUNKTION_DE,
	ORG_PARTNER_PROJEKTFUNKTION_EN
FROM rio.ORG_PARTNER_PROJEKTFUNKTION_L;

  CREATE OR REPLACE FORCE VIEW "API"."PERSON_PUBLIKATION" ("PUBLIKATION_ID", "MEDONLINE_PERSON_ID") AS 
  SELECT 
pp.PUBLIKATION_ID,
pm.MEDONLINE_PERSON_ID
FROM
RIO.PERSON_PUBLIKATION pp
JOIN
RIO.PERSON_MEDONLINE pm
ON pp.PERSON_ID = pm.PERSON_ID;

  CREATE OR REPLACE FORCE VIEW "API"."PROJEKT" ("PROJEKT_ID", "ORGEINHEIT_ID", "PROJEKT_TYP_ID", "KURZBEZEICHNUNG", "PROJEKTTITEL_DE", "PROJEKTTITEL_EN", "ORG_PARTNER_PROJEKTFUNKTION_ID", "PROJEKTLEITER_ID", "KONTAKTPERSON_ID", "PROJEKT_STATUS_ID", "PROJEKT_URL", "ABSTRACT_DE", "ABSTRACT_EN", "PROJEKTBEGINN_GEPLANT", "PROJEKTBEGINN_EFFEKTIV", "PROJEKTENDE_GEPLANT", "PROJEKTENDE_EFFEKTIV", "VERGABE_ART_ID", "FORSCHUNG_ART_ID", "VERANSTALTUNG_ART_ID", "STUDIE_ART_ID", "SPRACHE_ID") AS 
  SELECT
	p.PROJEKT_ID,
	o.MEDONLINE_ID ORGEINHEIT_ID,
	p.PROJEKT_TYP_ID,
	p.KURZBEZEICHNUNG,
	p.PROJEKTTITEL_DE,
	p.PROJEKTTITEL_EN,
	p.ORG_PARTNER_PROJEKTFUNKTION_ID,
	pm_pl.MEDONLINE_PERSON_ID PROJEKTLEITER_ID,
	pm_kp.MEDONLINE_PERSON_ID KONTAKTPERSON_ID,
	p.PROJEKT_STATUS_ID,
	p.PROJEKT_URL,
	p.ABSTRACT_DE,
	p.ABSTRACT_EN,
	p.PROJEKTBEGINN_GEPLANT,
	p.PROJEKTBEGINN_EFFEKTIV,
	p.PROJEKTENDE_GEPLANT,
	p.PROJEKTENDE_EFFEKTIV,
	p.VERGABE_ART_ID,
	p.FORSCHUNG_ART_ID,
	p.VERANSTALTUNG_ART_ID,
	p.STUDIE_ART_ID,
	p.SPRACHE_ID
FROM
	RIO.PROJEKT p
LEFT OUTER JOIN
	RIO.ORGEINHEIT o
	ON p.ORGEINHEIT_ID = o.ORGEINHEIT_ID
LEFT OUTER JOIN
	RIO.PERSON_MEDONLINE pm_pl
	ON p.PROJEKTLEITER_ID = pm_pl.PERSON_ID
LEFT OUTER JOIN
	RIO.PERSON_MEDONLINE pm_kp
	ON p.KONTAKTPERSON_ID = pm_kp.PERSON_ID;

  CREATE OR REPLACE FORCE VIEW "API"."PROJEKT_GELDGEBER" ("PROJEKT_ID", "GELDGEBER_ID", "HAUPTGELDGEBER_JA_NEIN") AS 
  SELECT
PROJEKT_ID,
GELDGEBER_ID,
HAUPTGELDGEBER_JA_NEIN
FROM rio.PROJEKT_GELDGEBER;

  CREATE OR REPLACE FORCE VIEW "API"."PROJEKT_STATUS_L" ("PROJEKT_STATUS_ID", "PROJEKT_STATUS") AS 
  SELECT
PROJEKT_STATUS_ID,
	PROJEKT_STATUS
FROM rio.PROJEKT_STATUS_L;

  CREATE OR REPLACE FORCE VIEW "API"."PROJEKT_TYP_L" ("PROJEKT_TYP_ID", "PROJEKT_TYP_DE", "PROJEKT_TYP_EN", "PROJEKT_TYP_KURZ_DE") AS 
  SELECT
PROJEKT_TYP_ID,
	PROJEKT_TYP_DE,
	PROJEKT_TYP_EN,
	PROJEKT_TYP_KURZ_DE
FROM rio.PROJEKT_TYP_L;

  CREATE OR REPLACE FORCE VIEW "API"."PUBLIKATION" ("PUBLIKATION_ID", "TITEL", "AUTOR", "JAHR", "QUELLE", "PUBLIKATION_TYP_ID", "PUBLIKATION_DOKUMENTTYP_ID", "SCI_ID", "PUBMED_ID", "DOI", "PMC_ID", "ABSTRACT") AS 
  SELECT 
            p.publikation_id,
            p.titel,
            p.autor,
            p.jahr,
            p.quelle,
            p.publikation_typ_id,
            p.publikation_dokumenttyp_id,
            p.sci_id,
            p.pubmed_id,
            p.doi,
            p.pmc_id,
            API.clob_to_blob(COALESCE(pi.abstracttext, psd.abstract)) abstract
        FROM
            rio.publikation p
        LEFT OUTER JOIN
            rio.pubmed_import pi
            ON (p.pubmed_id = pi.pubmed_id and pi.id not in (37452))
        LEFT OUTER JOIN
            rio.publikation_sci_daten psd
            ON (p.sci_id = psd.sci_id and p.publikation_id = psd.publikation_id);

  CREATE OR REPLACE FORCE VIEW "API"."PUBLIKATION_DOKUMENTTYP_L" ("PUBLIKATION_DOKUMENTTYP_ID", "PUBLIKATION_DOKUMENTTYP_DE", "PUBLIKATION_DOKUMENTTYP_EN") AS 
  SELECT "PUBLIKATION_DOKUMENTTYP_ID","PUBLIKATION_DOKUMENTTYP_DE","PUBLIKATION_DOKUMENTTYP_EN" FROM RIO.PUBLIKATION_DOKUMENTTYP_L;

  CREATE OR REPLACE FORCE VIEW "API"."PUBLIKATION_TEST" ("PUBLIKATION_ID", "AUTOR", "JAHR", "QUELLE", "PUBLIKATION_TYP_ID", "PUBLIKATION_DOKUMENTTYP_ID", "SCI_ID", "PUBMED_ID", "DOI", "PMC_ID", "ABSTRACT") AS 
  SELECT 
            p.publikation_id,
            p.autor,
            p.jahr,
            p.quelle,
            p.publikation_typ_id,
            p.publikation_dokumenttyp_id,
            p.sci_id,
            p.pubmed_id,
            p.doi,
            p.pmc_id,
            COALESCE(pi.abstracttext, psd.abstract) abstract
        FROM
            rio.publikation p
        LEFT OUTER JOIN
            rio.pubmed_import pi
            ON (p.pubmed_id = pi.pubmed_id and pi.id not in (37452))
        LEFT OUTER JOIN
            rio.publikation_sci_daten psd
            ON (p.sci_id = psd.sci_id and p.publikation_id = psd.publikation_id);

  CREATE OR REPLACE FORCE VIEW "API"."PUBLIKATION_TYP_L" ("PUBLIKATION_TYP_ID", "PUBLIKATION_TYP_DE", "PUBLIKATION_TYP_EN", "SORTIERUNG_ID") AS 
  SELECT "PUBLIKATION_TYP_ID","PUBLIKATION_TYP_DE","PUBLIKATION_TYP_EN","SORTIERUNG_ID" FROM RIO.PUBLIKATION_TYP_L;

  CREATE OR REPLACE FORCE VIEW "API"."SPRACHE_L" ("SPRACHE_ID", "SPRACHE_DE", "SPRACHE_EN", "SPRACHE_EN_KURZ") AS 
  SELECT
SPRACHE_ID,
	SPRACHE_DE,
	SPRACHE_EN,
	SPRACHE_EN_KURZ
FROM rio.SPRACHE_L;

  CREATE OR REPLACE FORCE VIEW "API"."STUDIE_ART_L" ("STUDIE_ART_ID", "STUDIE_ART_DE", "STUDIE_ART_EN") AS 
  SELECT
STUDIE_ART_ID,
	STUDIE_ART_DE,
	STUDIE_ART_EN
FROM rio.STUDIE_ART_L;

  CREATE OR REPLACE FORCE VIEW "API"."VERANSTALTUNG_ART_L" ("VERANSTALTUNG_ART_ID", "VERANSTALTUNG_ART_DE", "VERANSTALTUNG_ART_EN") AS 
  SELECT
VERANSTALTUNG_ART_ID,
	VERANSTALTUNG_ART_DE,
	VERANSTALTUNG_ART_EN
FROM rio.VERANSTALTUNG_ART_L;

  CREATE OR REPLACE FORCE VIEW "API"."VERGABE_ART_L" ("VERGABE_ART_ID", "VERGABE_ART_DE", "VERGABE_ART_EN") AS 
  SELECT
VERGABE_ART_ID,
	VERGABE_ART_DE,
	VERGABE_ART_EN
FROM rio.VERGABE_ART_L;
