# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from ...base.fields import ForeignDataWrapperKey


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campusonline', '0002_building_floor_room_roomcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('campusonline', ForeignDataWrapperKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='campusonline.Building')),
            ],
        ),
    ]
