# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campusonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('short', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'campusonline_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'campusonline_floor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('name_short', models.CharField(blank=True, max_length=256, null=True)),
                ('name_full', models.CharField(blank=True, max_length=256, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=1, max_digits=65535, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=65535, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'campusonline_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'campusonline_room_category',
                'managed': False,
            },
        ),
    ]
