# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0009_course_coursegroup_coursegroupterm_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False, 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'managed': False, 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False, 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False, 'ordering': ('name_full', 'title')},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'managed': False, 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'ordering': ('last_name', 'first_name')},
        ),
    ]
