# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0011_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('show_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'campusonline_event',
                'managed': False,
            },
        ),
    ]
