# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0016_mitteilungsblatt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=256)),
                ('issue', models.CharField(max_length=256)),
                ('published', models.DateTimeField()),
                ('teaser', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'campusonline_bulletin',
                'managed': False,
            },
        ),
    ]
