# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 08:05
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_person";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."personen";
        """,
        """
        CREATE FOREIGN TABLE "campusonline"."personen" (
            PERS_NR numeric,
            PERS_VORNAME varchar,
            PERS_FAMNAM varchar,
            PERS_TITEL varchar,
            PERS_SEX varchar,
            PERS_BENUTZERNAME varchar,
            PERS_SPRECHSTUNDE varchar,
            PERS_ZUSATZ_INFO varchar,
            PERS_PROFILBILD varchar,
            RAUM_NR numeric
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'PERSON_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_person" AS SELECT
            pers_nr ::integer AS id,
            pers_vorname AS first_name,
            pers_famnam AS last_name,
            pers_titel AS title,
            pers_sex AS sex,
            pers_benutzername AS username,
            pers_sprechstunde AS consultation,
            pers_zusatz_info AS appendix,
            pers_profilbild AS avatar,
            raum_nr ::integer AS room_id
        FROM "campusonline"."personen"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_person";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."personen";
        """,
        """
        CREATE FOREIGN TABLE "campusonline"."personen" (
            NR numeric,
            VORNAME varchar,
            FAMILIENNAME varchar,
            TITEL varchar,
            RAUM_NR numeric
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'PERSONEN_RAUM_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_person" AS SELECT
            nr ::integer AS id,
            vorname AS first_name,
            familienname AS last_name,
            titel AS title,
            raum_nr ::integer AS room_id
        FROM "campusonline"."personen"
        WITH DATA;
        """,
    ]

    dependencies = [
        ('campusonline', '0018_indices'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
