# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 09:21
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."organisationen";
        """,
        """
        CREATE FOREIGN TABLE "campusonline"."organisationen" (
            NR numeric,
            NAME_KURZ varchar,
            ORG_NAME varchar,
            BASISORGANISATION numeric,
            TYP varchar,
            ADRESSE varchar,
            EMAIL_ADRESSE varchar,
            TELEFON_NUMMER varchar,
            WWW_HOMEPAGE varchar,
            SORT_HIERARCHIE numeric
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'ORGANISATIONEN_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_organization" AS SELECT
            nr::integer AS id,
            org_name AS name,
            name_kurz AS short,
            basisorganisation::integer AS parent_id,
            sort_hierarchie::integer AS sib_order,
            typ AS category,
            adresse AS address,
            email_adresse AS email,
            telefon_nummer AS phone,
            www_homepage AS url
        FROM "campusonline"."organisationen"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."organisationen";
        """,
        """
        CREATE FOREIGN TABLE "campusonline"."organisationen" (
            NR numeric,
            ORG_NAME varchar,
            ADRESSE varchar,
            EMAIL_ADRESSE varchar,
            TELEFON_NUMMER varchar,
            WWW_HOMEPAGE varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'ORGANISATIONEN_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_organization" AS SELECT
            nr::integer AS id,
            org_name AS name,
            adresse AS address,
            email_adresse AS email,
            telefon_nummer AS phone,
            www_homepage AS url
        FROM "campusonline"."organisationen"
        WITH DATA;
        """,
    ]

    dependencies = [
        ('campusonline', '0020_auto_20180828_1050'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
