# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0022_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'campusonline_function',
                'ordering': ('name', 'category'),
                'managed': False,
            },
        ),
    ]
