# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:08
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        CREATE FOREIGN TABLE "campusonline"."pers_org_funk" (
            PERS_NR numeric,
            ORG_NR numeric,
            FUNK_NR numeric
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'PERS_ORG_FUNK_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_personorganizationfunction" AS SELECT
            format('%s-%s-%s', pers_nr::integer, org_nr::integer, funk_nr::integer) AS id,
            pers_nr::integer AS person_id,
            org_nr::integer AS organization_id,
            funk_nr::integer AS function_id
        FROM "campusonline"."pers_org_funk"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_personorganizationfunction";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."pers_org_funk";
        """,
    ]

    dependencies = [
        ('campusonline', '0023_function'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
