# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    forward = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization";
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_organization" AS SELECT
            nr::integer AS id,
            org_name AS name,
            name_kurz AS short,
            basisorganisation::integer AS parent_id,
            sort_hierarchie::integer AS sib_order,
            typ AS category,
            CASE trim(both ' ' from organisationen.adresse) WHEN '' THEN NULL ELSE trim(both ' ' from organisationen.adresse) END AS address,
            CASE trim(both ' ' from organisationen.email_adresse) WHEN '' THEN NULL ELSE trim(both ' ' from organisationen.email_adresse) END AS email,
            CASE trim(both ' ' from organisationen.telefon_nummer) WHEN '' THEN NULL ELSE trim(both ' ' from organisationen.telefon_nummer) END AS phone,
            CASE trim(both ' ' from organisationen.www_homepage) WHEN '' THEN NULL ELSE trim(both ' ' from organisationen.www_homepage) END AS url
        FROM "campusonline"."organisationen"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization";
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_organization" AS SELECT
            nr::integer AS id,
            org_name AS name,
            name_kurz AS short,
            basisorganisation::integer AS parent_id,
            sort_hierarchie::integer AS sib_order,
            typ AS category,
            adresse AS address,
            email_adresse AS email,
            telefon_nummer AS phone,
            www_homepage AS url
        FROM "campusonline"."organisationen"
        WITH DATA;
        """,
    ]

    dependencies = [
        ('campusonline', '0025_personorganizationfunction'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
