# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE UNIQUE INDEX campusonline_function_id_idx ON "public"."campusonline_function" ("id");
        ''',
        '''
        CREATE INDEX campusonline_function_name_idx ON "public"."campusonline_function" ("name");
        ''',
        '''
        CREATE UNIQUE INDEX campusonline_organization_id_idx ON "public"."campusonline_organization" ("id");
        ''',
        '''
        CREATE INDEX campusonline_organization_name_idx ON "public"."campusonline_organization" ("name");
        ''',
        '''
        CREATE INDEX campusonline_organization_short_idx ON "public"."campusonline_organization" ("short");
        ''',
        '''
        CREATE INDEX campusonline_organization_parent_id_idx ON "public"."campusonline_organization" ("parent_id");
        ''',
        '''
        CREATE INDEX campusonline_organization_sib_order_idx ON "public"."campusonline_organization" ("sib_order");
        ''',
        '''
        CREATE INDEX campusonline_organization_category_idx ON "public"."campusonline_organization" ("category");
        ''',
        '''
        CREATE UNIQUE INDEX campusonline_person_id_idx ON "public"."campusonline_person" ("id");
        ''',
        '''
        CREATE INDEX campusonline_person_first_name_idx ON "public"."campusonline_person" ("first_name");
        ''',
        '''
        CREATE INDEX campusonline_person_last_name_idx ON "public"."campusonline_person" ("last_name");
        ''',
        '''
        CREATE INDEX campusonline_person_sex_idx ON "public"."campusonline_person" ("sex");
        ''',
        '''
        CREATE INDEX campusonline_person_username_idx ON "public"."campusonline_person" ("username");
        ''',
        '''
        CREATE INDEX campusonline_person_room_id_idx ON "public"."campusonline_person" ("room_id");
        ''',
        '''
        CREATE UNIQUE INDEX campusonline_personorganizationfunction_id_idx ON "public"."campusonline_personorganizationfunction" ("id");
        ''',
        '''
        CREATE INDEX campusonline_personorganizationfunction_person_id_idx ON "public"."campusonline_personorganizationfunction" ("person_id");
        ''',
        '''
        CREATE INDEX campusonline_personorganizationfunction_organization_id_idx ON "public"."campusonline_personorganizationfunction" ("organization_id");
        ''',
        '''
        CREATE INDEX campusonline_personorganizationfunction_function_id_idx ON "public"."campusonline_personorganizationfunction" ("function_id");
        ''',
    ]

    reverse = [
        '''
        DROP INDEX IF EXISTS campusonline_personorganizationfunction_function_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_personorganizationfunction_organization_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_personorganizationfunction_person_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_personorganizationfunction_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_person_room_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_person_username_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_person_sex_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_person_last_name_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_person_first_name_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_person_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_organization_category_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_organization_sib_order_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_organization_parent_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_organization_short_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_organization_name_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_organization_id_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_function_name_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_function_id_idx;
        ''',
    ]

    dependencies = [
        ('campusonline', '0026_organization_empty_strings'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
