# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0029_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionList',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'campusonline_distributionlist',
                'ordering': ('name',),
                'managed': False,
            },
        ),
    ]
