# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0034_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionListInternal',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('persons', models.ManyToManyField(db_constraint=False, related_name='distribution_list_internal', to='campusonline.Person')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
