# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0036_distributionlist_union'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'get_latest_by': 'published', 'managed': False, 'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='bulletinpage',
            name='bulletin',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='campusonline.Bulletin'),
        ),
    ]
