# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0038_auto_20190128_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpage',
            name='clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bulletinpage',
            unique_together=set([('bulletin', 'index')]),
        ),
    ]
