# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0040_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinpage',
            options={'ordering': ('-bulletin', 'index')},
        ),
    ]
