# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0041_auto_20190205_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpage',
            name='harvest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulletinpage',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
