# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    forward = [
        """
        ALTER FOREIGN TABLE "campusonline"."stud_lv_anw" OPTIONS (
            ADD primary_key 'BUCHUNG_NR'
        );
        """,
    ]
    reverse = [
        """
        ALTER FOREIGN TABLE "campusonline"."stud_lv_anw" OPTIONS (
            DROP primary_key
        );
        """,
    ]

    dependencies = [
        ('campusonline', '0042_auto_20190206_1640'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
