# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0043_stud_lv_anw_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroupterm',
            options={'get_latest_by': 'start', 'managed': False, 'ordering': ('start', 'end'), 'permissions': (('view_coursegroupterm', 'Can view course group term'),)},
        ),
    ]
