# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 16:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='key',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
