# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('lti', '0003_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('role', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
