# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_country_funder_fundercategory_language_project_projectcategory_projectevent_projectgrant_projectpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoProjectCategory',
            fields=[
                ('id', models.OneToOneField(db_column='id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='research.ProjectCategory')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoProjectStatus',
            fields=[
                ('id', models.OneToOneField(db_column='id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='research.ProjectStatus')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
