# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE MATERIALIZED VIEW "public"."research_projectcategory" AS SELECT
            t.PROJEKT_TYP_ID::integer AS id,
            t.PROJEKT_TYP_DE AS name,
            t.PROJEKT_TYP_KURZ_DE AS short,
            COALESCE(d.public, FALSE) AS public
        FROM
            "research"."projekt_typ" AS t
        LEFT OUTER JOIN
            "public"."research_djangoprojectcategory" AS d
            ON t.PROJEKT_TYP_ID::integer = d.id
        ''',
        '''
        CREATE UNIQUE INDEX research_projectcategory_id_idx ON "public"."research_projectcategory" ("id");
        ''',
        '''
        CREATE MATERIALIZED VIEW "public"."research_projectstatus" AS SELECT
            s.PROJEKT_STATUS_ID::integer AS id,
            s.PROJEKT_STATUS AS name,
            COALESCE(d.public, FALSE) AS public
        FROM
            "research"."projekt_status" AS s
        LEFT OUTER JOIN
            "public"."research_djangoprojectstatus" AS d
            ON s.PROJEKT_STATUS_ID::integer = d.id
        ''',
        '''
        CREATE UNIQUE INDEX research_projectstatus_id_idx ON "public"."research_projectstatus" ("id");
        ''',
    ]

    reverse = [
        '''
        DROP INDEX IF EXISTS research_projectstatus_id_idx;
        ''',
        '''
        DROP MATERIALIZED VIEW IF EXISTS "public"."research_projectstatus";
        ''',
        '''
        DROP INDEX IF EXISTS research_publicationcategory_id_idx;
        ''',
        '''
        DROP MATERIALIZED VIEW IF EXISTS "public"."research_publicationcategory";
        ''',
    ]

    dependencies = [
        ('research', '0003_djangoprojectcategory_djangoprojectstatus'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
