# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_public_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'research_classification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'research_education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'research_expertise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'research_knowledge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'research_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'research_publicationauthorship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationOrganization',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('assigned', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'research_publicationorganization',
                'managed': False,
            },
        ),
    ]
