# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('short', models.TextField()),
                ('description', models.TextField()),
                ('mode', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('running', models.BooleanField()),
            ],
            options={
                'db_table': 'research_bidding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiddingDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('time', models.CharField(blank=True, max_length=16, null=True)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'research_biddingdeadline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiddingEndowment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'research_biddingendowment',
                'managed': False,
            },
        ),
    ]
