# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128)),
                ('dn', models.CharField(max_length=512)),
                ('filter', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('username_field', models.CharField(max_length=128)),
                ('email_field', models.CharField(max_length=128)),
            ],
        ),
    ]
