# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networktoken', '0004_login'),
    ]

    forward = [
        '''
        CREATE VIEW "radius"."protocol" AS SELECT
            n.username AS username,
            n.password AS pass,
            n.response AS reply,
            n.created AS authdate
        FROM "public"."networktoken_login" n;
        ''',
    ]

    reverse = [
        '''
        DROP VIEW "radius"."protocol";
        ''',
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
