# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 08:15
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        CREATE FOREIGN TABLE "campusonline"."gebaeude" (
            GEBAEUDE_NR numeric,
            NAME varchar,
            KURZBEZEICHNUNG varchar,
            STRASSE_HAUSNUMMER varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'GEBAEUDE_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE FOREIGN TABLE "campusonline"."stockwerk" (
            NR numeric,
            KURZBEZEICHNUNG varchar,
            NAME varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'STOCKWERK_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE FOREIGN TABLE "campusonline"."raum_kategorie" (
            NR numeric,
            NAME_DE varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'RAUM_TYPEN_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE FOREIGN TABLE "campusonline"."raum" (
            RAUM_NR numeric,
            RAUM_BEZ varchar,
            GEBAEUDE_NR numeric,
            GEBAEUDE varchar,
            STOCKWERK_NR numeric,
            STOCKWERK varchar,
            RAUM varchar,
            RAUM_NUMMER varchar,
            FLAECHE numeric,
            HOEHE numeric,
            ORG_NR numeric,
            ORGANISATION varchar,
            RAUMTYP numeric
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'RAUM_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE VIEW "public"."campusonline_building" AS SELECT
            gebaeude_nr::integer AS id,
            name,
            kurzbezeichnung AS short,
            strasse_hausnummer AS address
        FROM "campusonline"."gebaeude";
        """,
        """
        CREATE VIEW "public"."campusonline_floor" AS SELECT
            nr ::integer AS id,
            kurzbezeichnung AS short,
            name
        FROM "campusonline"."stockwerk";
        """,
        """
        CREATE VIEW "public"."campusonline_room_category" AS SELECT
            nr ::integer AS id,
            name_de AS name
        FROM "campusonline"."raum_kategorie";
        """,
        """
        CREATE VIEW "public"."campusonline_room" AS SELECT
            raum_nr ::integer AS id,
            raum_bez AS title,
            gebaeude_nr ::integer AS building_id,
            stockwerk_nr ::integer AS floor_id,
            raum AS name_short,
            raum_nummer AS name_full,
            flaeche AS area,
            hoehe AS height,
            organisation AS organization,
            raumtyp ::integer AS category_id
        FROM "campusonline"."raum";
        """,
    ]
    reverse = [
        """
        DROP VIEW IF EXISTS "public"."campusonline_room";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_room_category";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_floor";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_building";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."gebaeude";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."stockwerk";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."raum";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."raum_kategorie";
        """,
    ]

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
