# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    forward = [
        """
        DROP VIEW IF EXISTS "public"."campusonline_room";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_room_category";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_floor";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_building";
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_building" AS SELECT
            gebaeude_nr::integer AS id,
            name,
            kurzbezeichnung AS short,
            strasse_hausnummer AS address
        FROM "campusonline"."gebaeude"
        WITH DATA;
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_floor" AS SELECT
            nr ::integer AS id,
            kurzbezeichnung AS short,
            name
        FROM "campusonline"."stockwerk"
        WITH DATA;
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_room_category" AS SELECT
            nr ::integer AS id,
            name_de AS name
        FROM "campusonline"."raum_kategorie"
        WITH DATA;
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_room" AS SELECT
            raum_nr ::integer AS id,
            raum_bez AS title,
            gebaeude_nr ::integer AS building_id,
            stockwerk_nr ::integer AS floor_id,
            raum AS name_short,
            raum_nummer AS name_full,
            flaeche AS area,
            hoehe AS height,
            organisation AS organization,
            raumtyp ::integer AS category_id
        FROM "campusonline"."raum"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_room";
        """,
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_room_category";
        """,
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_floor";
        """,
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_building";
        """,
        """
        CREATE VIEW "public"."campusonline_building" AS SELECT
            gebaeude_nr::integer AS id,
            name,
            kurzbezeichnung AS short,
            strasse_hausnummer AS address
        FROM "campusonline"."gebaeude";
        """,
        """
        CREATE VIEW "public"."campusonline_floor" AS SELECT
            nr ::integer AS id,
            kurzbezeichnung AS short,
            name
        FROM "campusonline"."stockwerk";
        """,
        """
        CREATE VIEW "public"."campusonline_room_category" AS SELECT
            nr ::integer AS id,
            name_de AS name
        FROM "campusonline"."raum_kategorie";
        """,
        """
        CREATE VIEW "public"."campusonline_room" AS SELECT
            raum_nr ::integer AS id,
            raum_bez AS title,
            gebaeude_nr ::integer AS building_id,
            stockwerk_nr ::integer AS floor_id,
            raum AS name_short,
            raum_nummer AS name_full,
            flaeche AS area,
            hoehe AS height,
            organisation AS organization,
            raumtyp ::integer AS category_id
        FROM "campusonline"."raum";
        """,
    ]

    dependencies = [
        ('campusonline', '0002_building_floor_room_roomcategory'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
