# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE FOREIGN TABLE "campusonline"."stud_lv_anw" (
            BUCHUNG_NR numeric,
            STUD_NR numeric,
            GRP_NR numeric,
            TERMIN_NR numeric,
            ANM_BEGIN timestamp,
            ANM_ENDE timestamp,
            GESENDET timestamp,
            VERARB timestamp
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'STUD_LV_ANW',
            db_url '{}'
        );
        '''.format(settings.MULTICORN.get('campusonline')),
    ]

    reverse = [
        '''
        DROP FOREIGN TABLE IF EXISTS "campusonline"."stud_lv_anw";
        ''',
    ]

    dependencies = [
        ('campusonline', '0013_course_group_term'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
