# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE FOREIGN TABLE "campusonline"."mitteilungsblatt" (
            NR numeric,
            STUDIENJAHR varchar,
            STUECK varchar,
            AUSGABEDATUM timestamp,
            ZUSATZ_INFO varchar,
            LINK varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'MITTEILUNGSBLATT_V',
            db_url '{}'
        );
        '''.format(settings.MULTICORN.get('campusonline')),
        '''
        CREATE MATERIALIZED VIEW "public"."campusonline_bulletin" AS SELECT
            nr::integer AS id,
            studienjahr AS academic_year,
            stueck AS issue,
            (ausgabedatum AT TIME ZONE 'Europe/Vienna') ::timestamptz AS published,
            zusatz_info AS teaser,
            link as url
        FROM "campusonline"."mitteilungsblatt"
        WITH DATA;
        ''',
        '''
        CREATE INDEX campusonline_bulletin_id_idx ON "public"."campusonline_bulletin" ("id");
        ''',
        '''
        CREATE INDEX campusonline_bulletin_issue_idx ON "public"."campusonline_bulletin" ("issue");
        ''',
        '''
        CREATE INDEX campusonline_bulletin_published_idx ON "public"."campusonline_bulletin" ("published");
        ''',
    ]

    reverse = [
        '''
        DROP INDEX IF EXISTS campusonline_bulletin_published_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_bulletin_issue_idx;
        ''',
        '''
        DROP INDEX IF EXISTS campusonline_bulletin_id_idx;
        ''',
        '''
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_bulletin";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "campusonline"."mitteilungsblatt";
        ''',
    ]

    dependencies = [
        ('campusonline', '0015_auto_20180725_1913'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
