# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 12:22
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        CREATE FOREIGN TABLE "campusonline"."personen_organisationen" (
            PERSON_NR numeric,
            ORG_NR numeric
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'PERSONEN_ORGANISATIONEN_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_person_organization" AS SELECT
            person_nr::integer AS person_id,
            org_nr::integer AS organization_id
        FROM "campusonline"."personen_organisationen"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_person_organization";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."personen_organisationen";
        """,
    ]

    dependencies = [
        ('campusonline', '0031_functions'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
