# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 13:43
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_distributionlist_person";
        """,
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_distributionlist";
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_distributionlist" AS SELECT
            (profil_nr::integer)::varchar AS id,
            profil_name AS name
        FROM "campusonline"."verteilerliste"
        UNION
        SELECT
            id,
            name
        FROM "public"."campusonline_distributionlistinternal"
        WITH DATA;
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_distributionlist_person" AS SELECT
            (profil_nr::integer)::varchar AS distributionlist_id,
            pers_nr::integer AS person_id
        FROM "campusonline"."verteilerliste_person"
        UNION
        SELECT
            distributionlistinternal_id AS distributionlist_id,
            person_id
        FROM "public"."campusonline_distributionlistinternal_persons"
        WITH DATA;
        """,
    ]
    reverse = [
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_distributionlist_person";
        """,
        """
        DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_distributionlist";
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_distributionlist" AS SELECT
            profil_nr::integer AS id,
            profil_name AS name
        FROM "campusonline"."verteilerliste"
        WITH DATA;
        """,
        """
        CREATE MATERIALIZED VIEW "public"."campusonline_distributionlist_person" AS SELECT
            profil_nr::integer AS distributionlist_id,
            pers_nr::integer AS person_id
        FROM "campusonline"."verteilerliste_person"
        WITH DATA;
        """,
    ]

    dependencies = [
        ('campusonline', '0035_distributionlistinternal'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
