# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 13:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='outline',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857),
        ),
    ]
