# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20170418_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='door',
        ),
    ]
