# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_remove_edge_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={},
        ),
        migrations.RemoveField(
            model_name='floor',
            name='order',
        ),
        migrations.AddField(
            model_name='floor',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Level'),
        ),
    ]
