# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_copy_level_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='node',
            name='floor',
        ),
    ]
