# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_auto_20170630_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edgecategory',
            options={'ordering': ('weight',)},
        ),
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
