# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_room_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='icon',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='css_class',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='font_key',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
