# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_auto_20170829_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pointofinterestinstance',
            options={},
        ),
    ]
