# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 08:15
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
    ]
    reverse = [
        '''
        DROP VIEW IF EXISTS "public"."typo3_news";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."typo3_event";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."typo3_calendar";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."typo3_category";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."typo3_language";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."language";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."category";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."event";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."calendar";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."news";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."campusonline_room";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."campusonline_room_category";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."campusonline_floor";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."campusonline_building";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "campusonline"."gebaeude";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "campusonline"."stockwerk";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "campusonline"."raum";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "campusonline"."raum_kategorie";
        ''',
        '''
        DROP SERVER IF EXISTS "sqlalchemy";
        ''',
    ]

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
