# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 08:15
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        """
        CREATE SERVER sqlalchemy
        FOREIGN DATA WRAPPER multicorn
        OPTIONS (
            wrapper 'outpost.fdw.OutpostFdw'
        );
        """,
        """
        CREATE FOREIGN TABLE "campusonline"."gebaeude" (
            GEBAEUDE_NR numeric,
            NAME varchar,
            KURZBEZEICHNUNG varchar,
            STRASSE_HAUSNUMMER varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'GEBAEUDE_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE FOREIGN TABLE "campusonline"."stockwerk" (
            NR numeric,
            KURZBEZEICHNUNG varchar,
            NAME varchar
        )
        SERVER sqlalchemy OPTiONS (
            tablename 'STOCKWERK_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE FOREIGN TABLE "campusonline"."raum" (
            RAUM_NR numeric,
            RAUM_BEZ varchar,
            GEBAEUDE_NR numeric,
            GEBAEUDE varchar,
            STOCKWERK_NR numeric,
            STOCKWERK varchar,
            RAUM varchar,
            RAUM_NUMMER varchar,
            FLAECHE numeric,
            HOEHE numeric,
            ORG_NR numeric,
            ORGANISATION varchar
        )
        SERVER sqlalchemy OPTiONS (
            tablename 'RAUM_V',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('campusonline')),
        """
        CREATE FOREIGN TABLE "typo3"."category" (
            uid integer,
            tstamp integer,
            crdate integer,
            deleted integer,
            hidden integer,
            starttime integer,
            endtime integer,
            sys_language_uid integer,
            title text,
            description text,
            parent integer,
            items integer,
            images integer,
            shortcut integer,
            calendar_id integer,
            tx_odsosm_marker integer
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'sys_category',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('typo3')),
        """
        CREATE FOREIGN TABLE "typo3"."news" (
            uid integer,
            tstamp integer,
            crdate integer,
            sys_language_uid integer,
            deleted integer,
            hidden integer,
            starttime integer,
            endtime integer,
            sorting integer,
            title text,
            teaser text,
            bodytext text,
            datetime integer,
            archive integer,
            author text,
            author_email text,
            categories integer,
            related integer,
            related_from integer,
            related_files text,
            related_links text,
            type varchar,
            keywords text,
            tags integer,
            media text,
            internalurl text,
            externalurl text,
            istopnews integer,
            content_elements text,
            path_segment text,
            alternative_title text,
            description text,
            fal_related_files integer,
            fal_media integer
        )
        SERVER sqlalchemy
        OPTIONS (
            tablename 'tx_news_domain_model_news',
            db_url '{}'
        );
        """.format(settings.MULTICORN.get('typo3')),
        """
        CREATE VIEW "public"."typo3_category" AS SELECT
            uid AS id,
            CASE
                crdate
            WHEN
                0
            THEN
                NULL
            ELSE
                to_timestamp(crdate)
            END AS created,
            sys_language_uid AS language_id,
            CASE
                starttime
            WHEN
                0
            THEN
                NULL
            ELSE
                to_timestamp(starttime)
            END AS start,
            CASE
                endtime
            WHEN
                0
            THEN
                NULL
            ELSE
                to_timestamp(endtime)
            END AS end,
            title,
            description,
            parent,
            calendar_id,
            tx_odsosm_marker AS marker
        FROM "typo3"."category"
        WHERE
            deleted = 0 AND
            hidden = 0;
        """,
        """
        CREATE VIEW "public"."typo3_news" AS SELECT
            uid AS id,
            CASE
                crdate
            WHEN
                0
            THEN
                NULL
            ELSE
                to_timestamp(crdate)
            END AS created,
            sys_language_uid AS language_id,
            CASE
                starttime
            WHEN
                0
            THEN
                NULL
            ELSE
                to_timestamp(starttime)
            END AS start,
            CASE
                endtime
            WHEN
                0
            THEN
                NULL
            ELSE
                to_timestamp(endtime)
            END AS end,
            title,
            teaser,
            bodytext AS body,
            author,
            author_email AS email,
            keywords,
            tags,
            istopnews = 1 AS topnews,
            description
        FROM "typo3"."news"
        WHERE
            deleted = 0 AND
            hidden = 0 AND
            archive = 0;
        """,
        """
        CREATE VIEW "public"."campusonline_building" AS SELECT
            gebaeude_nr::integer AS id,
            name,
            kurzbezeichnung AS short,
            strasse_hausnummer AS address
        FROM "campusonline"."gebaeude";
        """,
        """
        CREATE VIEW "public"."campusonline_floor" AS SELECT
            nr ::integer AS id,
            kurzbezeichnung AS short,
            name
        FROM "campusonline"."stockwerk";
        """,
        """
        CREATE VIEW "public"."campusonline_room" AS SELECT
            raum_nr ::integer AS id,
            raum_bez AS title,
            gebaeude_nr ::integer AS building_id,
            gebaeude AS building,
            stockwerk_nr ::integer AS floor_id,
            stockwerk AS floor,
            raum AS name_short,
            raum_nummer AS name_full,
            flaeche AS area,
            hoehe AS height,
            org_nr ::integer AS organization_id,
            organisation AS organization
        FROM "campusonline"."raum";
        """,
    ]
    reverse = [
        """
        DROP VIEW IF EXISTS "public"."campusonline_room";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_floor";
        """,
        """
        DROP VIEW IF EXISTS "public"."campusonline_building";
        """,
        """
        DROP VIEW IF EXISTS "public"."typo3_news";
        """,
        """
        DROP VIEW IF EXISTS "public"."typo3_category";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."gebaeude";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."stockwerk";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "campusonline"."raum";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "typo3"."category";
        """,
        """
        DROP FOREIGN TABLE IF EXISTS "typo3"."news";
        """,
        """
        DROP SERVER IF EXISTS sqlalchemy;
        """,
    ]

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
