# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0002_calendar_category_event_language_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ('start', 'end')},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'ordering': ('-datetime',)},
        ),
    ]
