# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 11:18
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE FOREIGN TABLE "typo3"."sys_category_record_mm" (
            uid_local integer,
            uid_foreign integer,
            tablenames varchar,
            sorting integer,
            sorting_foreign integer,
            fieldname varchar
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'sys_category_record_mm',
            db_url '{}'
        );
        '''.format(settings.MULTICORN.get('typo3')),
        '''
        CREATE VIEW "public"."typo3_newscategory" AS SELECT
            CONCAT(uid_local, '-', uid_foreign) AS id,
            uid_local AS category_id,
            uid_foreign AS news_id
        FROM "typo3"."sys_category_record_mm"
        WHERE
            tablenames = 'tx_news_domain_model_news';
        ''',
    ]
    reverse = [
        '''
        DROP VIEW IF EXISTS "public"."typo3_newscategory";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."sys_category_record_mm";
        ''',
    ]

    dependencies = [
        ('typo3', '0004_auto_20170906_1021'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
