# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0005_category_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'typo3_newscategory',
                'managed': False,
            },
        ),
    ]
