# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 07:54
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE FOREIGN TABLE "typo3"."group" (
            uid integer,
            pid integer,
            tstamp integer,
            title varchar,
            hidden integer,
            deleted integer
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'fe_groups',
            db_url '{typo3}'
        );
        '''.format(typo3=settings.MULTICORN.get('typo3')),
        '''
        CREATE MATERIALIZED VIEW "public"."typo3_group" AS SELECT
            uid AS id,
            pid AS page,
            CASE trim(both ' ' from title) WHEN '' THEN NULL ELSE trim(both ' ' from title) END AS title
        FROM
            typo3.group
        WHERE
            hidden = 0 AND
            deleted = 0
        ''',
        '''
        CREATE MATERIALIZED VIEW "public"."typo3_news_group" AS SELECT
            uid AS news_id,
            unnest(string_to_array(fe_group, ',')::integer[]) AS group_id
        FROM
            typo3.news
        WHERE
            fe_group IS NOT NULL
        ''',
    ]
    reverse = [
        '''
        DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_news_group";
        ''',
        '''
        DROP MATERIALIZED VIEW IF EXISTS "public"."typo3_group";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."group";
        ''',
    ]

    dependencies = [
        ('typo3', '0012_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
