# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0013_news_fe_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'typo3_group',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'start', 'managed': False, 'ordering': ('start', 'end')},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'get_latest_by': 'datetime', 'managed': False, 'ordering': ('-datetime',)},
        ),
    ]
