# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0015_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('sib_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'typo3_eventcategory',
                'managed': False,
            },
        ),
    ]
