# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0017_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('mimetype', models.CharField(blank=True, max_length=256, null=True)),
                ('filename', models.CharField(blank=True, max_length=256, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'typo3_media',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='eventmedia',
            options={'managed': False, 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='newsmedia',
            options={'managed': False, 'ordering': ('order',)},
        ),
    ]
