# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0018_auto_20180919_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmedia',
            options={'managed': False, 'ordering': ('-preview', '-order')},
        ),
        migrations.AlterModelOptions(
            name='newsmedia',
            options={'managed': False, 'ordering': ('-preview', '-order')},
        ),
    ]
