# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0020_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSource',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('private', models.BooleanField(default=True)),
            ],
        ),
    ]
