# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typo3', '0021_djangosource'),
    ]

    forward = [
        '''
        CREATE VIEW "public"."typo3_source" AS
        SELECT
        t.id AS id,
        t.title AS title,
        COALESCE(d.private, FALSE) AS private
        FROM "typo3"."source_typo3" AS t
        LEFT OUTER JOIN
            "public"."typo3_djangosource" AS d
            ON t.id = d.id
        ''',
    ]

    reverse = [
        '''
        DROP VIEW IF EXISTS "public"."typo3_source";
        ''',
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
