# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_epiphan_provision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorder',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='active',
            new_name='enabled',
        ),
    ]
