# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 14:28
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import outpost.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_auto_20180206_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epiphansource',
            old_name='preview',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='epiphansource',
            name='audio',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=outpost.base.utils.Uuid4Upload),
        ),
    ]
