# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_recording_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
