# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import outpost.django.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0004_user_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.TextField(validators=[outpost.django.base.validators.PublicKeyValidator()]),
        ),
    ]
