# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0007_convert_to_staffuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
    ]
