# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0008_remove_user_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffuser',
            old_name='coperson',
            new_name='person',
        ),
    ]
