# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0045_course_group_term_filterd'),
        ('salt', '0009_auto_20190327_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salt.User')),
                ('person', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='campusonline.Student')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('salt.user',),
        ),
    ]
