# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20170810_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='geo.Room'),
        ),
    ]
