# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170820_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epiphanrecording',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.EpiphanChannel'),
        ),
    ]
