# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_recorder_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='epiphan',
            name='provision',
            field=models.BooleanField(default=False),
        ),
    ]
