# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
from ...base.utils import Uuid4Upload


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_zipstreamexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpiphanSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('preview', imagekit.models.fields.ProcessedImageField(upload_to=Uuid4Upload)),
                ('epiphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Epiphan')),
            ],
        ),
    ]
