# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 08:07
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
from ...base.utils import Uuid4Upload


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_epiphansource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epiphansource',
            name='preview',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Uuid4Upload),
        ),
    ]
