# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_auto_20171129_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='retention',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
