# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_auto_20180308_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
