# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 12:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0012_event'),
        ('video', '0022_recording_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='course_group_term',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campusonline.CourseGroupTerm'),
        ),
        migrations.AddField(
            model_name='recording',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
