# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_auto_20180312_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
