# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0027_auto_20180615_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='epiphansource',
            name='name',
            field=models.CharField(default='HDMI', max_length=64),
            preserve_default=False,
        ),
    ]
