# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 12:29
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    forward = [
        '''
        CREATE FOREIGN TABLE "typo3"."cal_category" (
            uid integer,
            pid integer,
            parent_category integer,
            tstamp integer,
            deleted integer,
            hidden integer,
            title varchar,
            sorting integer,
            calendar_id integer,
            sys_language_uid integer
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'tx_cal_category',
            db_url '{}'
        );
        '''.format(settings.MULTICORN.get('typo3')),
        '''
        CREATE FOREIGN TABLE "typo3"."cal_event_category" (
            uid_local integer,
            uid_foreign integer,
            tablenames varchar,
            sorting integer
        )
        SERVER sqlalchemy OPTIONS (
            tablename 'tx_cal_event_category_mm',
            db_url '{}'
        );
        '''.format(settings.MULTICORN.get('typo3')),
        '''
        CREATE VIEW "public"."typo3_eventcategory" AS SELECT
            uid AS id,
            pid AS page,
            parent_category AS parent_id,
            sorting AS sib_order,
            calendar_id,
            title,
            sys_language_uid AS language_id
        FROM "typo3"."cal_category"
        WHERE
            hidden = 0 AND
            deleted = 0;
        ''',
        '''
        CREATE VIEW "public"."typo3_event_eventcategory" AS SELECT
            uid_local AS event_id,
            uid_foreign AS eventcategory_id
        FROM "typo3"."cal_event_category";
        ''',
    ]
    reverse = [
        '''
        DROP VIEW IF EXISTS "public"."typo3_event_eventcategory";
        ''',
        '''
        DROP VIEW IF EXISTS "public"."typo3_eventcategory";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."cal_event_category";
        ''',
        '''
        DROP FOREIGN TABLE IF EXISTS "typo3"."cal_category";
        ''',
    ]

    dependencies = [
        ('typo3', '0014_auto_20180906_1035'),
    ]

    operations = [
        migrations.RunSQL(
            forward,
            reverse
        )
    ]
