# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_icon'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterestInstance',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.Node')),
            ],
            options={
                'abstract': False,
            },
            bases=('geo.node',),
        ),
        migrations.RemoveField(
            model_name='pointofinterestcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='pointofinterestcategory',
            name='node_ptr',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='category',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='color',
            field=models.CharField(default='007b3c', max_length=6),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Icon'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(default='POI', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PointOfInterestCategory',
        ),
        migrations.AddField(
            model_name='pointofinterestinstance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.PointOfInterest'),
        ),
    ]
