# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walls',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.Floor'),
            preserve_default=False,
        ),
    ]
