# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 14:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_walls_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('major', models.PositiveIntegerField()),
                ('minor', models.PositiveIntegerField()),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('deployed', models.DateTimeField(auto_now_add=True)),
                ('seen', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Floor')),
            ],
        ),
    ]
