# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_beacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
