# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_beacon_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='floor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
