# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '__first__'),
        ('geo', '0005_auto_20170306_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campusonline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campusonline.Building'),
        ),
        migrations.AddField(
            model_name='floor',
            name='campusonline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campusonline.Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='campusonline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campusonline.Room'),
        ),
    ]
