# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Level = apps.get_model('geo', 'Level')
    if Level.objects.all().exists():
        level = Level.objects.first()
    else:
        level = Level(name='Default Migration')
        level.save()
    Beacon = apps.get_model('geo', 'Beacon')
    for beacon in Beacon.objects.all():
        if beacon.floor.level:
            beacon.level = beacon.floor.level
        else:
            beacon.level = level
        beacon.save()
    Node = apps.get_model('geo', 'Node')
    for node in Node.objects.all():
        if node.floor.level:
            node.level = node.floor.level
        else:
            node.level = level
        node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_add_level'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
